import { Category, Product } from '../../entities';

// Enhanced categories with subcategory hierarchy
export const mockCategoriesWithSubcategories: Category[] = [
  // ELECTRONICS - Main Category
  {
    id: '1',
    slug: 'electronics',
    name: 'Electronics',
    description: 'Latest electronic devices and gadgets',
    image: 'https://picsum.photos/300/200?random=cat1',
    productCount: 45,
    isActive: true,
    sortOrder: 1,
  },
  
  // Electronics Subcategories
  {
    id: '1-1',
    slug: 'smartphones',
    name: 'Smartphones',
    description: 'Latest smartphones and mobile devices',
    image: 'https://picsum.photos/300/200?random=subcat11',
    parentId: '1',
    productCount: 12,
    isActive: true,
    sortOrder: 1,
  },
  {
    id: '1-2',
    slug: 'laptops',
    name: 'Laptops & Computers',
    description: 'Laptops, desktops, and computer accessories',
    image: 'https://picsum.photos/300/200?random=subcat12',
    parentId: '1',
    productCount: 8,
    isActive: true,
    sortOrder: 2,
  },
  {
    id: '1-3',
    slug: 'audio',
    name: 'Audio & Headphones',
    description: 'Headphones, speakers, and audio equipment',
    image: 'https://picsum.photos/300/200?random=subcat13',
    parentId: '1',
    productCount: 15,
    isActive: true,
    sortOrder: 3,
  },
  {
    id: '1-4',
    slug: 'smart-home',
    name: 'Smart Home',
    description: 'Smart home devices and IoT products',
    image: 'https://picsum.photos/300/200?random=subcat14',
    parentId: '1',
    productCount: 10,
    isActive: true,
    sortOrder: 4,
  },

  // CLOTHING - Main Category
  {
    id: '2',
    slug: 'clothing',
    name: 'Clothing',
    description: 'Fashion and apparel for all occasions',
    image: 'https://picsum.photos/300/200?random=cat2',
    productCount: 60,
    isActive: true,
    sortOrder: 2,
  },
  
  // Clothing Subcategories
  {
    id: '2-1',
    slug: 'mens-clothing',
    name: "Men's Clothing",
    description: 'Clothing and accessories for men',
    image: 'https://picsum.photos/300/200?random=subcat21',
    parentId: '2',
    productCount: 25,
    isActive: true,
    sortOrder: 1,
  },
  {
    id: '2-2',
    slug: 'womens-clothing',
    name: "Women's Clothing",
    description: 'Clothing and accessories for women',
    image: 'https://picsum.photos/300/200?random=subcat22',
    parentId: '2',
    productCount: 30,
    isActive: true,
    sortOrder: 2,
  },
  {
    id: '2-3',
    slug: 'shoes',
    name: 'Shoes & Footwear',
    description: 'Shoes, boots, and footwear for all occasions',
    image: 'https://picsum.photos/300/200?random=subcat23',
    parentId: '2',
    productCount: 18,
    isActive: true,
    sortOrder: 3,
  },
  {
    id: '2-4',
    slug: 'accessories',
    name: 'Accessories',
    description: 'Bags, jewelry, watches, and accessories',
    image: 'https://picsum.photos/300/200?random=subcat24',
    parentId: '2',
    productCount: 12,
    isActive: true,
    sortOrder: 4,
  },

  // HOME & GARDEN - Main Category
  {
    id: '3',
    slug: 'home-garden',
    name: 'Home & Garden',
    description: 'Everything for your home and garden',
    image: 'https://picsum.photos/300/200?random=cat3',
    productCount: 40,
    isActive: true,
    sortOrder: 3,
  },
  
  // Home & Garden Subcategories
  {
    id: '3-1',
    slug: 'furniture',
    name: 'Furniture',
    description: 'Indoor and outdoor furniture',
    image: 'https://picsum.photos/300/200?random=subcat31',
    parentId: '3',
    productCount: 15,
    isActive: true,
    sortOrder: 1,
  },
  {
    id: '3-2',
    slug: 'kitchen-dining',
    name: 'Kitchen & Dining',
    description: 'Kitchen appliances, cookware, and dining essentials',
    image: 'https://picsum.photos/300/200?random=subcat32',
    parentId: '3',
    productCount: 12,
    isActive: true,
    sortOrder: 2,
  },
  {
    id: '3-3',
    slug: 'garden',
    name: 'Garden & Outdoor',
    description: 'Gardening tools, plants, and outdoor equipment',
    image: 'https://picsum.photos/300/200?random=subcat33',
    parentId: '3',
    productCount: 8,
    isActive: true,
    sortOrder: 3,
  },
  {
    id: '3-4',
    slug: 'home-decor',
    name: 'Home Decor',
    description: 'Decorative items, lighting, and home accessories',
    image: 'https://picsum.photos/300/200?random=subcat34',
    parentId: '3',
    productCount: 10,
    isActive: true,
    sortOrder: 4,
  },

  // SPORTS & OUTDOORS - Main Category
  {
    id: '4',
    slug: 'sports',
    name: 'Sports & Outdoors',
    description: 'Sports equipment and outdoor gear',
    image: 'https://picsum.photos/300/200?random=cat4',
    productCount: 35,
    isActive: true,
    sortOrder: 4,
  },
  
  // Sports Subcategories
  {
    id: '4-1',
    slug: 'fitness',
    name: 'Fitness & Exercise',
    description: 'Gym equipment, weights, and fitness accessories',
    image: 'https://picsum.photos/300/200?random=subcat41',
    parentId: '4',
    productCount: 12,
    isActive: true,
    sortOrder: 1,
  },
  {
    id: '4-2',
    slug: 'outdoor-recreation',
    name: 'Outdoor Recreation',
    description: 'Camping, hiking, and outdoor adventure gear',
    image: 'https://picsum.photos/300/200?random=subcat42',
    parentId: '4',
    productCount: 10,
    isActive: true,
    sortOrder: 2,
  },
  {
    id: '4-3',
    slug: 'team-sports',
    name: 'Team Sports',
    description: 'Equipment for football, basketball, soccer, and more',
    image: 'https://picsum.photos/300/200?random=subcat43',
    parentId: '4',
    productCount: 8,
    isActive: true,
    sortOrder: 3,
  },
  {
    id: '4-4',
    slug: 'water-sports',
    name: 'Water Sports',
    description: 'Swimming, surfing, and water activity equipment',
    image: 'https://picsum.photos/300/200?random=subcat44',
    parentId: '4',
    productCount: 5,
    isActive: true,
    sortOrder: 4,
  },

  // BOOKS - Main Category
  {
    id: '5',
    slug: 'books',
    name: 'Books',
    description: 'Books, audiobooks, and educational materials',
    image: 'https://picsum.photos/300/200?random=cat5',
    productCount: 30,
    isActive: true,
    sortOrder: 5,
  },
  
  // Books Subcategories
  {
    id: '5-1',
    slug: 'fiction',
    name: 'Fiction',
    description: 'Novels, short stories, and literary fiction',
    image: 'https://picsum.photos/300/200?random=subcat51',
    parentId: '5',
    productCount: 12,
    isActive: true,
    sortOrder: 1,
  },
  {
    id: '5-2',
    slug: 'non-fiction',
    name: 'Non-Fiction',
    description: 'Biographies, history, science, and educational books',
    image: 'https://picsum.photos/300/200?random=subcat52',
    parentId: '5',
    productCount: 10,
    isActive: true,
    sortOrder: 2,
  },
  {
    id: '5-3',
    slug: 'educational',
    name: 'Educational & Textbooks',
    description: 'Academic textbooks and educational materials',
    image: 'https://picsum.photos/300/200?random=subcat53',
    parentId: '5',
    productCount: 8,
    isActive: true,
    sortOrder: 3,
  },

  // HEALTH & BEAUTY - Main Category
  {
    id: '6',
    slug: 'health-beauty',
    name: 'Health & Beauty',
    description: 'Health, wellness, and beauty products',
    image: 'https://picsum.photos/300/200?random=cat6',
    productCount: 25,
    isActive: true,
    sortOrder: 6,
  },
  
  // Health & Beauty Subcategories
  {
    id: '6-1',
    slug: 'skincare',
    name: 'Skincare',
    description: 'Skincare products and treatments',
    image: 'https://picsum.photos/300/200?random=subcat61',
    parentId: '6',
    productCount: 10,
    isActive: true,
    sortOrder: 1,
  },
  {
    id: '6-2',
    slug: 'makeup',
    name: 'Makeup & Cosmetics',
    description: 'Makeup, cosmetics, and beauty tools',
    image: 'https://picsum.photos/300/200?random=subcat62',
    parentId: '6',
    productCount: 8,
    isActive: true,
    sortOrder: 2,
  },
  {
    id: '6-3',
    slug: 'health-supplements',
    name: 'Health & Supplements',
    description: 'Vitamins, supplements, and health products',
    image: 'https://picsum.photos/300/200?random=subcat63',
    parentId: '6',
    productCount: 7,
    isActive: true,
    sortOrder: 3,
  },
];

// Sample products with subcategory mapping
export const mockProductsWithSubcategories: Product[] = [
  // Electronics > Audio products
  {
    id: 'audio-1',
    slug: 'wireless-headphones-pro',
    title: 'Wireless Headphones Pro',
    description: 'Premium wireless headphones with active noise cancellation and 30-hour battery life.',
    price: 299.99,
    originalPrice: 399.99,
    currency: 'USD',
    images: ['https://picsum.photos/600/600?random=audio1'],
    category: 'electronics',
    subcategory: 'audio',
    tags: ['wireless', 'audio', 'premium'],
    rating: 4.8,
    reviewCount: 156,
    stock: 25,
    sku: 'WHP-001',
    brand: 'AudioTech',
    features: ['Active Noise Cancellation', '30h Battery', 'Quick Charge', 'Premium Build'],
    specifications: {
      'Battery Life': '30 hours',
      'Charging Time': '2 hours',
      'Weight': '250g',
      'Connectivity': 'Bluetooth 5.0',
    },
    isNew: false,
    isFeatured: true,
    isOnSale: true,
    dateAdded: '2024-01-10T10:30:00Z',
    dateModified: '2024-01-10T10:30:00Z',
  },
  
  // Electronics > Smartphones
  {
    id: 'phone-1',
    slug: 'flagship-smartphone-256gb',
    title: 'Flagship Smartphone 256GB',
    description: 'Latest flagship smartphone with advanced camera system and 5G connectivity.',
    price: 899.99,
    currency: 'USD',
    images: ['https://picsum.photos/600/600?random=phone1'],
    category: 'electronics',
    subcategory: 'smartphones',
    tags: ['5G', 'smartphone', 'flagship'],
    rating: 4.7,
    reviewCount: 234,
    stock: 15,
    sku: 'FS-256',
    brand: 'TechCorp',
    features: ['5G Ready', 'Triple Camera', '256GB Storage', 'Wireless Charging'],
    specifications: {
      'Storage': '256GB',
      'RAM': '8GB',
      'Screen Size': '6.7 inches',
      'Battery': '4500mAh',
    },
    isNew: true,
    isFeatured: true,
    isOnSale: false,
    dateAdded: '2024-01-15T14:20:00Z',
    dateModified: '2024-01-15T14:20:00Z',
  },

  // Clothing > Men's Clothing
  {
    id: 'men-1',
    slug: 'classic-denim-jacket',
    title: 'Classic Denim Jacket',
    description: 'Timeless denim jacket with vintage wash and comfortable fit.',
    price: 89.99,
    originalPrice: 119.99,
    currency: 'USD',
    images: ['https://picsum.photos/600/600?random=men1'],
    category: 'clothing',
    subcategory: 'mens-clothing',
    tags: ['denim', 'vintage', 'jacket'],
    rating: 4.5,
    reviewCount: 67,
    stock: 20,
    sku: 'CDJ-001',
    brand: 'Denim Co',
    features: ['Classic Cut', 'Vintage Wash', 'Button Closure', 'Multiple Pockets'],
    specifications: {
      'Material': '100% Cotton Denim',
      'Wash': 'Medium Blue',
      'Fit': 'Regular',
      'Care': 'Machine Wash',
    },
    isNew: false,
    isFeatured: true,
    isOnSale: true,
    dateAdded: '2024-01-12T16:45:00Z',
    dateModified: '2024-01-12T16:45:00Z',
  },

  // Home & Garden > Kitchen & Dining
  {
    id: 'kitchen-1',
    slug: 'ceramic-dinnerware-set',
    title: 'Ceramic Dinnerware Set 16-Piece',
    description: 'Elegant ceramic dinnerware set perfect for family meals and entertaining guests.',
    price: 129.99,
    currency: 'USD',
    images: ['https://picsum.photos/600/600?random=kitchen1'],
    category: 'home-garden',
    subcategory: 'kitchen-dining',
    tags: ['ceramic', 'dinnerware', 'kitchen'],
    rating: 4.6,
    reviewCount: 91,
    stock: 30,
    sku: 'CDS-16',
    brand: 'HomeStyle',
    features: ['Dishwasher Safe', 'Microwave Safe', 'Chip Resistant', 'Modern Design'],
    specifications: {
      'Material': 'Ceramic',
      'Pieces': '16 (Service for 4)',
      'Care': 'Dishwasher Safe',
      'Style': 'Modern',
    },
    isNew: true,
    isFeatured: false,
    isOnSale: false,
    dateAdded: '2024-01-08T11:15:00Z',
    dateModified: '2024-01-08T11:15:00Z',
  },
];
